package controleur;

public enum TypeOrdre {

    SHOW_MENU, SHOW_AJOUT, CHARGER_GENRES, SHOW_FILMS, CHARGER_FILMS, SHOW_FILMSGENRE, VIDER_CHAMPS, NOM_EXISTANT, GENRE_INEXISTANT,CHAMPS_VIDE,CHARGER_FILMS_PAR_GENRE;

}
